import 'package:flutter/material.dart';
import '../core/constants/app_constants.dart';
import '../models/exercise.dart';

class ExerciseService {
  static List<ExerciseModel> getAllExercises() {
    return [
      ExerciseModel(
        id: AppConstants.exercisePinching,
        title: 'PINCH MASTER',
        subtitle: 'Fine Motor Coordination',
        description: 'Improve finger coordination and precision by targeting and pinching objects.',
        icon: Icons.pinch_rounded,
        category: 'Distal Motor Control',
        therapeuticGoal: 'Enhance thumb-to-index opposition force and precision release.',
        tutorialSteps: [
          'Move your hand toward the illuminated sphere.',
          'Pinch using your thumb and index finger (click and hold).',
          'Maintain your pinch hold while moving the object toward the recovery portal.',
          'Release your fingers when centered inside the target zone.',
        ],
        levels: [
          const ExerciseLevel(
            levelNumber: 1,
            name: 'Level 1 – Gentle Starter (3 Targets)',
            difficulty: 'Beginner',
            isUnlocked: true,
            stars: 3,
            isCompleted: true,
            bestAccuracy: 95.0,
            targetCount: 3,
            durationSeconds: 45,
            tolerance: 1.4,
          ),
          const ExerciseLevel(
            levelNumber: 2,
            name: 'Level 2 – Steady Flow (4 Targets)',
            difficulty: 'Easy',
            isUnlocked: true,
            stars: 3,
            isCompleted: true,
            bestAccuracy: 92.0,
            targetCount: 4,
            durationSeconds: 40,
            tolerance: 1.2,
          ),
          const ExerciseLevel(
            levelNumber: 3,
            name: 'Level 3 – Precision Orbit (5 Targets)',
            difficulty: 'Medium',
            isUnlocked: true,
            stars: 2,
            isCompleted: true,
            bestAccuracy: 88.0,
            targetCount: 5,
            durationSeconds: 35,
            tolerance: 1.0,
          ),
          const ExerciseLevel(
            levelNumber: 4,
            name: 'Level 4 – Speed Pinch (6 Targets)',
            difficulty: 'Hard',
            isUnlocked: true,
            stars: 1,
            isCompleted: false,
            targetCount: 6,
            durationSeconds: 28,
            tolerance: 0.8,
          ),
          const ExerciseLevel(
            levelNumber: 5,
            name: 'Level 5 – Micro-Precision (8 Targets)',
            difficulty: 'Advanced',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 8,
            durationSeconds: 24,
            tolerance: 0.65,
          ),
        ],
      ),
      ExerciseModel(
        id: AppConstants.exerciseHolding,
        title: 'STEADY HOLD',
        subtitle: 'Isometric Stability',
        description: 'Improve grip stability and sustained muscle control by holding inside the tolerance zone.',
        icon: Icons.front_hand_rounded,
        category: 'Endurance & Tremor Reduction',
        therapeuticGoal: 'Stabilize tremor amplitude and reinforce prolonged isometric muscle activation.',
        tutorialSteps: [
          'Position your hand pointer over the core stabilizer orb.',
          'Grip and hold firmly inside the glowing stability ring.',
          'Maintain steady pressure without drifting outside the zone.',
          'Hold until the stability progress bar reaches 100%.',
        ],
        levels: [
          const ExerciseLevel(
            levelNumber: 1,
            name: 'Level 1 – Gentle Stability (3s Hold)',
            difficulty: 'Beginner',
            isUnlocked: true,
            stars: 3,
            isCompleted: true,
            bestAccuracy: 94.0,
            targetCount: 3,
            durationSeconds: 3,
            tolerance: 1.5,
          ),
          const ExerciseLevel(
            levelNumber: 2,
            name: 'Level 2 – Sustained Control (5s Hold)',
            difficulty: 'Easy',
            isUnlocked: true,
            stars: 3,
            isCompleted: true,
            bestAccuracy: 89.0,
            targetCount: 3,
            durationSeconds: 5,
            tolerance: 1.25,
          ),
          const ExerciseLevel(
            levelNumber: 3,
            name: 'Level 3 – Tremor Resistance (7s Hold)',
            difficulty: 'Medium',
            isUnlocked: true,
            stars: 2,
            isCompleted: false,
            targetCount: 4,
            durationSeconds: 7,
            tolerance: 1.0,
          ),
          const ExerciseLevel(
            levelNumber: 4,
            name: 'Level 4 – Deep Endurance (9s Hold)',
            difficulty: 'Hard',
            isUnlocked: true,
            stars: 1,
            isCompleted: false,
            targetCount: 4,
            durationSeconds: 9,
            tolerance: 0.8,
          ),
          const ExerciseLevel(
            levelNumber: 5,
            name: 'Level 5 – Master Iron Grip (12s Hold)',
            difficulty: 'Advanced',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 5,
            durationSeconds: 12,
            tolerance: 0.65,
          ),
        ],
      ),
      ExerciseModel(
        id: AppConstants.exerciseTracing,
        title: 'PATH TRACE',
        subtitle: 'Motor Trajectory & Precision',
        description: 'Improve movement precision and motor control by following illuminated rehabilitation corridors.',
        icon: Icons.timeline_rounded,
        category: 'Continuous Motor Guidance',
        therapeuticGoal: 'Enhance smooth pursuit kinematics and decrease deviation excursions.',
        tutorialSteps: [
          'Begin at the illuminated green START waypoint.',
          'Trace steadily along the glowing guidance corridor.',
          'Keep your movement centered to maintain high precision and avoid edge collisions.',
          'Reach the finish portal to complete the trajectory.',
        ],
        levels: [
          const ExerciseLevel(
            levelNumber: 1,
            name: 'Level 1 – Straight Bridge',
            difficulty: 'Beginner',
            isUnlocked: true,
            stars: 3,
            isCompleted: true,
            bestAccuracy: 90.0,
            targetCount: 1,
            durationSeconds: 35,
            tolerance: 1.4,
          ),
          const ExerciseLevel(
            levelNumber: 2,
            name: 'Level 2 – Zigzag Mountain Pass',
            difficulty: 'Easy',
            isUnlocked: true,
            stars: 2,
            isCompleted: true,
            bestAccuracy: 84.0,
            targetCount: 1,
            durationSeconds: 35,
            tolerance: 1.2,
          ),
          const ExerciseLevel(
            levelNumber: 3,
            name: 'Level 3 – S-Curve River of Light',
            difficulty: 'Medium',
            isUnlocked: true,
            stars: 1,
            isCompleted: false,
            targetCount: 1,
            durationSeconds: 40,
            tolerance: 1.0,
          ),
          const ExerciseLevel(
            levelNumber: 4,
            name: 'Level 4 – Sine Wave Rollercoaster',
            difficulty: 'Hard',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 1,
            durationSeconds: 45,
            tolerance: 0.8,
          ),
          const ExerciseLevel(
            levelNumber: 5,
            name: 'Level 5 – Cyber Winding Labyrinth',
            difficulty: 'Advanced',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 1,
            durationSeconds: 50,
            tolerance: 0.65,
          ),
        ],
      ),
      ExerciseModel(
        id: AppConstants.exerciseDragging,
        title: 'SHAPE DRAG',
        subtitle: 'Spatial Coordination',
        description: 'Improve coordination and controlled movement by matching geometric tokens into target slots.',
        icon: Icons.category_rounded,
        category: 'Spatial Manipulation',
        therapeuticGoal: 'Promote reach-and-place control, spatial matching, and hand stabilization.',
        tutorialSteps: [
          'Identify the active geometric shape on the board.',
          'Select and drag the shape with smooth, deliberate movement.',
          'Align it over the matching outlined target receptor.',
          'Release within the zone to snap into place.',
        ],
        levels: [
          const ExerciseLevel(
            levelNumber: 1,
            name: 'Level 1 – Tri-Color Shapes (3)',
            difficulty: 'Beginner',
            isUnlocked: true,
            stars: 3,
            isCompleted: true,
            bestAccuracy: 93.0,
            targetCount: 3,
            durationSeconds: 40,
            tolerance: 1.3,
          ),
          const ExerciseLevel(
            levelNumber: 2,
            name: 'Level 2 – Quadrant Matrix (4)',
            difficulty: 'Easy',
            isUnlocked: true,
            stars: 2,
            isCompleted: false,
            targetCount: 4,
            durationSeconds: 35,
            tolerance: 1.15,
          ),
          const ExerciseLevel(
            levelNumber: 3,
            name: 'Level 3 – Full Pentagon Suite (5)',
            difficulty: 'Medium',
            isUnlocked: true,
            stars: 1,
            isCompleted: false,
            targetCount: 5,
            durationSeconds: 32,
            tolerance: 0.95,
          ),
          const ExerciseLevel(
            levelNumber: 4,
            name: 'Level 4 – Speed Shuffle Match',
            difficulty: 'Hard',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 5,
            durationSeconds: 26,
            tolerance: 0.8,
          ),
          const ExerciseLevel(
            levelNumber: 5,
            name: 'Level 5 – Master Spatial Lock',
            difficulty: 'Advanced',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 5,
            durationSeconds: 22,
            tolerance: 0.65,
          ),
        ],
      ),
      ExerciseModel(
        id: AppConstants.exerciseGesture,
        title: 'GESTURE MATCH',
        subtitle: 'Hand Pose Recognition',
        description: 'Improve hand pose recognition and finger control by executing prompted rehabilitation gestures.',
        icon: Icons.pan_tool_alt_rounded,
        category: 'Neuromotor Finger Differentiation',
        therapeuticGoal: 'Strengthen individual digit flexor/extensor control and motor reaction speed.',
        tutorialSteps: [
          'Observe the target gesture displayed on the screen.',
          'Form the matching hand posture or tap the corresponding gesture selector.',
          'Confirm alignment inside the detection radar.',
          'Complete the sequence within the target reaction window.',
        ],
        levels: [
          const ExerciseLevel(
            levelNumber: 1,
            name: 'Level 1 – Core 3 Postures (3 Poses)',
            difficulty: 'Beginner',
            isUnlocked: true,
            stars: 3,
            isCompleted: true,
            bestAccuracy: 92.0,
            targetCount: 3,
            durationSeconds: 35,
            tolerance: 1.5,
          ),
          const ExerciseLevel(
            levelNumber: 2,
            name: 'Level 2 – 4 Gesture Sequence',
            difficulty: 'Easy',
            isUnlocked: true,
            stars: 2,
            isCompleted: false,
            targetCount: 4,
            durationSeconds: 32,
            tolerance: 1.25,
          ),
          const ExerciseLevel(
            levelNumber: 3,
            name: 'Level 3 – 5 Gestures Dynamic Pace',
            difficulty: 'Medium',
            isUnlocked: true,
            stars: 1,
            isCompleted: false,
            targetCount: 5,
            durationSeconds: 28,
            tolerance: 1.0,
          ),
          const ExerciseLevel(
            levelNumber: 4,
            name: 'Level 4 – Rapid Reflex Alternation (6)',
            difficulty: 'Hard',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 6,
            durationSeconds: 25,
            tolerance: 0.8,
          ),
          const ExerciseLevel(
            levelNumber: 5,
            name: 'Level 5 – Master Neuromotor Rapid Fire',
            difficulty: 'Advanced',
            isUnlocked: true,
            stars: 0,
            isCompleted: false,
            targetCount: 8,
            durationSeconds: 20,
            tolerance: 0.65,
          ),
        ],
      ),
    ];
  }
}
